sudo: required

language: python

python:
- '3.6'
- '3.7'

install:
- pip install -U pip
- pip install .[test]

script:
- py.test
- prospector -M

branches:
  only: master

after_success:
- git config --global user.email "travis@travis-ci.com"
- git config --global user.name "Travis"
- git tag -a v$(python setup.py --version) -m "Travis build $TRAVIS_BUILD_NUMBER"
- git push origin --tags
- git fetch origin

deploy:
  provider: pypi
  skip_cleanup: true
  distributions: sdist
  user: eduardomourar
  password:
    secure: "Pfot8UXgkEgPv/QIzKlYetssoZSZSTZSSF0+Qq+7ySznethSt4ysMl3PsBYcju2sZAJkG4pQ37UpxIqoQ0Ni3iTUJO9DH0nQ/K/5G0mnXlMWTe/VjFwzTqXSmTAi85cdZsKHX2xW/efIBseB11SuxAdd30N4RS2nPoGEBM0JVY9oKNGAMqBxQJHoGMmrMHAuUzv8H5h1Tk7HwAe6GfD9MtFLfw2onuat9SZVqsdeNlMAu3F+t6AO4+esrrZXY0uM/KfdMWC84A14vXQSf5zpri9B/j/1Y/UZIDTr/B21PJFRg6VZ9AUkNT9mW6jpb7GjGblCKayzbpM2CY39ryj6G/37f5+XlbeDFrSBHK9r/nKXL7rvRrfoJwi9gux9zuoMaW+9jLqz3tQFCmamw6vCaqaOGMsc/JMBA1RJiQan1xKDzrNGFNo4erYhvEeaUhWXJuddFT7u2P6T4SE2xyXIL11pjuST508JJqy1u7Gwwuo6L/ocFCPEEz8wp+0efawPnyaDVGat7PcDW3prgHg7/FVfmeOOXBlJ30+h80gVfVu4FX3QRW5ISeBSWfGjOdSm41gUHgvHO2V9VdD7ib1vx4fg4mI4z2Z5uSTg1Guaklytk6aWGnb+7bjyc8QcnERmZlShyxBilaxl/IT4ttUW6igBfEE2VZyQAD9CLmZcMpA="
  on:
    tags: false
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
